FROM ubuntu:18.10
ARG BASEPATH=/root
ARG YANG_EXPLORER_PATH=${BASEPATH}/yang-explorer
EXPOSE 8000

RUN apt-get update
RUN apt-get install --no-install-recommends -y \
		gdebi-core \
		python3-dev \
		python-dev \
		libtool-bin \
		libcurl4-openssl-dev \
		libpcre3-dev \
		libssh-dev \
		libxml2-dev \
		libxslt1-dev \
        python-pip \
		python-setuptools \
        python-virtualenv \
        graphviz \
        git \
        zlib1g-dev \
		libydk \
		build-essential \
		cmake
RUN pip install --upgrade pip setuptools virtualenv

# YDK deps

RUN wget https://devhub.cisco.com/artifactory/debian-ydk/0.8.2/bionic/libydk-0.8.2-1.amd64.deb
RUN gdebi libydk-0.8.2-1.amd64.deb
WORKDIR ${BASEPATH}
RUN git clone https://github.com/CiscoDevNet/ydk-py.git
WORKDIR ydk-py/core
RUN python setup.py sdist
RUN pip install dist/ydk*.gz
WORKDIR ../ietf
RUN python setup.py sdist
RUN pip install dist/ydk*.gz
WORKDIR ../openconfig
RUN python setup.py sdist
RUN pip install dist/ydk*.gz
WORKDIR ../cisco-ios-xr
RUN python setup.py sdist
RUN pip install dist/ydk*.gz

# Yang Explorer itself
RUN mkdir -p ${YANG_EXPLORER_PATH}
WORKDIR ${YANG_EXPLORER_PATH}
COPY . .
RUN virtualenv v
RUN . v/bin/activate
RUN pip install -r requirements.txt

# Initialize yang explorer
WORKDIR ${YANG_EXPLORER_PATH}/server
RUN mkdir -p data/users
RUN mkdir -p data/session
RUN mkdir -p data/collections
RUN mkdir -p data/annotation
RUN python manage.py migrate
RUN python manage.py setupdb

CMD python manage.py runserver 0.0.0.0:8000
