FROM ubuntu:18.10
ARG BASEPATH=/root
ARG YANG_EXPLORER_PATH=${BASEPATH}/yang-explorer
EXPOSE 8000

RUN apt-get update
RUN apt-get install --no-install-recommends -y \
		gdebi-core \
		python3-dev \
		python-dev \
		python3-pip \
		python-pip \
		libtool-bin \
		libcurl4-openssl-dev \
		libpcre3-dev \
		libssh-dev \
		libxml2-dev \
		libxslt1-dev \
		graphviz \
		build-essential \
		clang \
		cmake
RUN pip install --upgrade pip setuptools virtualenv


# YDK deps
RUN pip install ydk-models-cisco-ios-xe
RUN pip install ydk-models-cisco-ios-xr

# Yang Explorer itself
RUN mkdir -p ${YANG_EXPLORER_PATH}
WORKDIR ${YANG_EXPLORER_PATH}
COPY . .
RUN virtualenv v
RUN . v/bin/activate
RUN pip install -r requirements.txt

# Initialize yang explorer
WORKDIR ${YANG_EXPLORER_PATH}/server
RUN mkdir -p data/users
RUN mkdir -p data/session
RUN mkdir -p data/collections
RUN mkdir -p data/annotation
RUN python manage.py migrate
RUN python manage.py setupdb

CMD python manage.py runserver 0.0.0.0:8000
